Class {
	#name : 'PvActionSettings',
	#superclass : 'Object',
	#instVars : [
		'mod1',
		'mod2',
		'mod3'
	],
	#category : 'Perspective-Command-Base',
	#package : 'Perspective',
	#tag : 'Command-Base'
}

{ #category : 'accessing' }
PvActionSettings >> mod1 [

	^ mod1
]

{ #category : 'accessing' }
PvActionSettings >> mod1: anObject [

	mod1 := anObject
]

{ #category : 'accessing' }
PvActionSettings >> mod2 [

	^ mod2
]

{ #category : 'accessing' }
PvActionSettings >> mod2: anObject [

	mod2 := anObject
]

{ #category : 'accessing' }
PvActionSettings >> mod3 [

	^ mod3
]

{ #category : 'accessing' }
PvActionSettings >> mod3: anObject [

	mod3 := anObject
]
