name: Build Pulsar

on:
  push:

jobs:
  test:
    runs-on: docker
    container:
      image: forge.smallworks.eu/pharo/build-env:ubuntu-24.04

    steps:
         
      - uses: actions/checkout@v4

      - name: Setup SSH
        env:
          CI_SSH_KEY: ${{ secrets.CI_SSH_KEY }}
        run: |
          mkdir -p /root/.ssh
          chmod 700 /root/.ssh
          printf "%s\n" "$CI_SSH_KEY" > /root/.ssh/id_ed25519
          chmod 600 /root/.ssh/id_ed25519
          ssh-keyscan forge.smallworks.eu >> /root/.ssh/known_hosts
          ssh-keyscan github.com >> /root/.ssh/known_hosts

      - name: Run build script
        run: |
          mkdir build && cd build
          python -u ../.ci/scripts/build.py
