name: Build Pulsar

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: docker
    container:
      image: forge.smallworks.eu/pharo/build-env:ubuntu-24.04

    steps:
         
      - uses: actions/checkout@v4

      - name: Setup SSH key
        env:
          CI_SSH_PRIVATE_KEY: ${{ secrets.CI_SSH_PRIVATE_KEY }}
          CI_SSH_PUBLIC_KEY: ${{ secrets.CI_SSH_PUBLIC_KEY }}
        run: |
          mkdir -p /root/.ssh
          chmod 700 /root/.ssh
          printf "%s" "$CI_SSH_PRIVATE_KEY" > /root/.ssh/id_ed25519
          printf "%s" "$CI_SSH_PUBLIC_KEY" > /root/.ssh/id_ed25519.pub
          chmod 600 /root/.ssh/id_ed25519
          chmod 600 /root/.ssh/id_ed25519.pub
          ssh-keyscan forge.smallworks.eu >> /root/.ssh/known_hosts
          ssh-keyscan github.com >> /root/.ssh/known_hosts

      - name: Run build script
        run: |
          mkdir -p build && cd build
          python -u ../.ci/scripts/build.py
          ls -l dist

      - name: Set nightly date
        if: github.event_name == 'schedule'
        run: |
          echo "NIGHTLY_DATE=$(date +%F)" >> $GITHUB_ENV
          echo "NIGHTLY_DATE=${{ env.NIGHTLY_DATE }}"
          ls -l dist

      - name: Upload nightly artifact
        if: github.event_name == 'schedule'
        run: |
          mv dist/Pulsar.tar.gz dist/Pulsar-${NIGHTLY_DATE}.tar.gz
          ls -l dist

      - name: Upload nightly artifact
        if: github.event_name == 'schedule'
        uses: actions/upload-artifact@v4
        with:
          name: nightly-build
          path: dist/Pulsar-${{ env.NIGHTLY_DATE }}.tar.gz

      - name: Set tag name
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "TAG_NAME=${{ github.ref_name }}"
          ls -l dist

      - name: Upload tagged artifact
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG="${{ github.ref_name }}"
          mv dist/Pulsar.tar.gz dist/Pulsar-${TAG_NAME}.tar.gz
          ls -l dist

      - name: Upload stable artifact
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: stable-build
          path: dist/Pulsar-${{ env.TAG_NAME }}.tar.gz