name: Release Pulsar

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: docker
    container:
      image: forge.smallworks.eu/pharo/build-env:ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key
        env:
          CI_SSH_PRIVATE_KEY: ${{ secrets.CI_SSH_PRIVATE_KEY }}
          CI_SSH_PUBLIC_KEY: ${{ secrets.CI_SSH_PUBLIC_KEY }}
        run: |
          mkdir -p /root/.ssh
          chmod 700 /root/.ssh
          printf "%s" "$CI_SSH_PRIVATE_KEY" > /root/.ssh/id_ed25519
          printf "%s" "$CI_SSH_PUBLIC_KEY" > /root/.ssh/id_ed25519.pub
          chmod 600 /root/.ssh/id_ed25519
          chmod 600 /root/.ssh/id_ed25519.pub
          ssh-keyscan forge.smallworks.eu >> /root/.ssh/known_hosts
          ssh-keyscan github.com >> /root/.ssh/known_hosts

      - name: Run build script
        run: |
          mkdir -p build && cd build
          python -u ../.ci/scripts/build.py --release

      - name: Set tag name
        run: |
          echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "TAG_NAME=${TAG_NAME}"

      - name: Rename release artifact
        run: |
          mv build/dist/Pulsar.tar.gz build/dist/Pulsar-${TAG_NAME}.tar.gz

      - name: Generate checksum
        run: |
          cd build/dist
          sha256sum Pulsar-${TAG_NAME}.tar.gz > Pulsar-${TAG_NAME}.tar.gz.sha256

      - name: Keep release artifact
        uses: actions/upload-artifact@v3
        with:
          name: stable-build
          path: build/dist/Pulsar-${{ env.TAG_NAME }}.tar.gz

      - name: Upload release artifacts to Packages
        run: |
          for FILE in \
            Pulsar-${TAG_NAME}.tar.gz \
            Pulsar-${TAG_NAME}.tar.gz.sha256
          do
            curl -f -X PUT \
              -H "Authorization: token $FORGEJO_TOKEN" \
              --upload-file build/dist/$FILE \
              "$FORGEJO_SERVER_URL/api/packages/$FORGEJO_REPOSITORY_OWNER/generic/builds/releases/${TAG_NAME}/$FILE"
          done