Class {
	#name : 'PulsarDebuggerContextInspector',
	#superclass : 'SpPresenter',
	#traits : 'PulsarTNotificationCenter + PulsarTPanelWindow + PulsarTSnapshot + SpTModel',
	#classTraits : 'PulsarTNotificationCenter classTrait + PulsarTPanelWindow classTrait + PulsarTSnapshot classTrait + SpTModel classTrait',
	#category : 'Pulsar-Browser-Tool-Debugger',
	#package : 'Pulsar-Browser',
	#tag : 'Tool-Debugger'
}
