#!/usr/bin/env python3
import buildenv
import pharoget
import subprocess
import argparse

from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPOSITORY_DIR = SCRIPT_DIR.parent.parent
BUILD_IMAGE_VERSION = None

def run(cmd):
    """Run shell command safely."""
    
    print(f"+ {' '.join(cmd)}")
    subprocess.run(cmd, check=True)

def evaluate_pharo_script(filename):
    """Run a Pharo command safely."""

    print("🏃‍➡️ Evaluating: ", filename)

    script = f"OpalCompiler new source: ('{filename}' asFileReference contents); evaluate."

    run([
        "pharo", 
        "--headless", 
        f"{buildenv.DEST_DIR}/{buildenv.DEST_IMAGE_NAME}.image", 
        "--no-default-preferences",
        "eval",
        "--save",           
        script ])

    print("✅ Done.")

def cleanup_local():
    """
    Clean up local directories generated by the build process.

    This function removes the `pharo-local` directory which contains local changes made to the Pharo image.
    """
    print("🧹 Cleaning up local directories")
    run(["rm", "-rf", f"{buildenv.DEST_DIR}/pharo-local"])
    print("✅ Done.")

def prepare_tarball():
    
    """
    Prepare a tarball for distribution.

    This function will create a tarball containing the Pharo image, changes file, and resources.
    The tarball will be named after the image name, and will be placed in the build directory.

    If there are not exactly one Pharo*.sources file in the build directory, a RuntimeError will be raised.

    :return: None
    """
    print("📦 Preparing tarball")
    
    dest = Path(buildenv.DEST_DIR)
    sources = list(dest.glob("Pharo*.sources"))

    if len(sources) != 1:
        raise RuntimeError(f"Expected exactly one Pharo*.sources file, found {sources}")

    run([
        "tar", 
        "-C", buildenv.DEST_DIR,        
        "-czf", 
        f"{buildenv.DEST_DIR}/{buildenv.DEST_IMAGE_NAME}.tar.gz", 
        f"{buildenv.DEST_IMAGE_NAME}.image", 
        f"{buildenv.DEST_IMAGE_NAME}.changes", 
        sources[0].name, 
        "pulsar-resources"])

    print("✅ Done.")

def copy_resources():
    """
    Copies the resources from the repository to the build directory.

    The resources will be copied into a
    directory named "pulsar-resources" inside the build directory.

    This function is useful for including the resources in the build
    artifact.

    """
    print("📦 Copying resources")
    run(["cp", "-r", f"{REPOSITORY_DIR}/resources", f"{buildenv.DEST_DIR}/pulsar-resources"])
    print("✅ Done.")

def main() -> None:
  
    parser = argparse.ArgumentParser(
        description="Build a Pulsar package."
    )
    parser.add_argument("-r", "--release", action="store_true", help="Prepare package as release")

    args = parser.parse_args()

    if args.release:
        BUILD_IMAGE_VERSION = buildenv.RELEASE_IMAGE_VERSION

    # Step. Download the Pulsar image  
    print("🌐 Downloading Pulsar image")
    pharoget.prepare_image(
        dest_dir=buildenv.DEST_DIR, 
        image_name=buildenv.DEST_IMAGE_NAME, 
        build=buildenv.BUILD_IMAGE_VERSION, 
        kill=True)
    # Step. Evaluate the pharo preparing scripts
    for script in [ "PreLoad.st", "Load.st", "PostLoad.st" ]:
        evaluate_pharo_script(f"{SCRIPT_DIR}/{script}")
    # Step. Copy resources
    copy_resources()
    # Step. Prepare tarball
    prepare_tarball()

    print("👍 Build Done.")


if __name__ == "__main__":
    main()